is_build_in_struct: false
libname: bot
struct_name: github.com/yaklang/yaklang/common/utils/bot.Config
description: ""
fields:
- structname: github.com/yaklang/yaklang/common/utils/bot.Config
  name: BotType
  param_alias: ""
  type_alias: ""
  description: ""
  type_str: string
- structname: github.com/yaklang/yaklang/common/utils/bot.Config
  name: Secret
  param_alias: ""
  type_alias: ""
  description: ""
  type_str: string
- structname: github.com/yaklang/yaklang/common/utils/bot.Config
  name: Webhook
  param_alias: ""
  type_alias: ""
  description: ""
  type_str: string
methods:
- ptr: true
  description: ""
  structname: github.com/yaklang/yaklang/common/utils/bot.Config
  name: SendMarkdown
  params:
  - name: v2
    param_alias: ""
    type_alias: ""
    description: ""
    type_str: string
  relative_struct_name: []
- ptr: true
  description: ""
  structname: github.com/yaklang/yaklang/common/utils/bot.Config
  name: SendText
  params:
  - name: v2
    param_alias: ""
    type_alias: ""
    description: ""
    type_str: string
  - name: v3
    param_alias: ""
    type_alias: ""
    description: ""
    type_str: '[]interface {}'
    is_variadic: true
  relative_struct_name: []
ptr_methods: []
