name: Vulinbox-Release

on:
  push:
    paths:
      - 'common/vulinbox/**'
      - 'common/vulinboxrunner/**'
      - '.github/workflows/vulinbox-release.yml'

jobs:
  build_and_release:
    strategy:
      matrix:
        os:
          - ubuntu-20.04
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set Yak Version by Tag
        uses: mad9000/actions-find-and-replace-string@1
        id: fetchtag
        with:
          source: ${{ github.ref }}
          find: 'refs/tags/'
          replace: ''
      - name: Print RELEASE_VERSION
        run: |
          echo "github actions's env VERSION: ${{ steps.fetchtag.outputs.value }}"
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.3

      - name: Install libpcap (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install libpcap-dev=1.9.1-3
        if: runner.os == 'Linux'

      - name: Build For Linux
        run: |
          go build -ldflags "-linkmode external -extldflags '-static' -s -w -X 'main.goVersion=$(go version)' -X 'main.gitHash=$(git show -s --format=%H)' -X 'main.buildTime=$(git show -s --format=%cd)' -X 'main.yakVersion=${{ steps.fetchtag.outputs.value }}'" -o "./vulinbox_$(go env GOOS)_$(go env GOARCH)" -v common/vulinboxrunner/vulinbox.go
        if: runner.os == 'Linux'

      - name: Upload Artifacts Linux
        uses: actions/upload-artifact@v2
        if: runner.os == 'Linux'
        with:
          name: vulinbox_linux_amd64
          path: ./vulinbox_linux_amd64